version: "3.9"
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: hello-api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: testdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db
volumes:
  db_data: