apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: bodanesemateus/hello-api
    argocd-image-updater.argoproj.io/bodanesemateus_hello-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    kustomize: {} 
    repoURL: 'https://github.com/bodanesemateus/k8s-kind-cluster.git'
    targetRevision: main
    path: k8s/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true