apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello-api=bodanesemateus/hello-api
    argocd-image-updater.argoproj.io/hello-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/hello-api.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/bodanesemateus/k8s-kind-cluster.git
    targetRevision: HEAD
    path: k8s/manifests
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true