apiVersion: v1  
kind: Secret  
metadata:
  name: argocd-image-updater-config
  namespace: argocd  
stringData:  
  log.level: debug  
  registries.conf: | 
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry-1.docker.io
  git.config: |  
    commit_message_template: "chore: update image to {{.NewTag}}"  # Template da mensagem de commit
    # {{.NewTag}} será substituído pela nova tag da imagem
    author_name: "ArgoCD Image Updater"  # Nome do autor do commit
    author_email: "argocd-image-updater@example.com"  # Email do autor do commi
  git-credentials: |
    https://bodanesemateus:$YOUR_GITHUB_TOKEN@github.com