apiVersion: v1
kind: Secret
metadata:
  name: repo-github-k8s-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository 
stringData:
  type: git 
  url: https://github.com/bodanesemateus/k8s-kind-cluster.git
  username: $YOUR_GITHUB_USERNAME
  password: $YOUR_GITHUB_TOKEN
  log.level: debug