apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: hello-api-3-0-0
        image: bodanesemateus/hello-api:3.0.0
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_NAME
          value: testdb
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 8000