apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
spec:
  selector:
    app: hello-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
  - name: metrics
    port: 8002
    targetPort: 8002
    nodePort: 30082
  type: NodePort