apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: default
type: Opaque
data:
  # Credenciais do elastic (admin)
  elastic-password: dGVzdGUxMjM=  # teste123
  elastic-username: ZWxhc3RpYw==  # elastic
  
  # Credenciais específicas do Kibana
  kibana-password: dGVzdGUxMjM=  # teste123
  kibana-username: a2liYW5hX3N5c3RlbQ==  # kibana_system